name: Running level 5

on:
  schedule:
    - cron: "30 22 * * *"   # 04:00 AM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    environment: production   # ðŸ‘ˆ REQUIRED

    env:
      API_KEY1: ${{ vars.API_KEY1 }}
      API_KEY2: ${{ vars.API_KEY2 }}
      API_KEY3: ${{ vars.API_KEY3 }}
      API_KEY4: ${{ vars.API_KEY4 }}
      API_KEY5: ${{ vars.API_KEY5 }}
      API_KEY6: ${{ vars.API_KEY6 }}
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run level 5 script
        run: python level5/level5.py
