name: Running level 5

on:
  schedule:
    - cron: "30 22 * * *"   # 04:00 AM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      API_KEY1: ${{ secrets.API_KEY1 }}
      API_KEY2: ${{ secrets.API_KEY2 }}
      API_KEY3: ${{ secrets.API_KEY3 }}
      API_KEY4: ${{ secrets.API_KEY4 }}
      API_KEY5: ${{ secrets.API_KEY5 }}
      API_KEY6: ${{ secrets.API_KEY6 }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run script
        run: python level5/level5.py
